name: CI

on:
  push:

    branches: 
    - '*'
    tags:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Compile TS
      run: npm run compileTs --if-present

    - name: Build
      run: npm run build --if-present

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TMS.js
        path: ./Compile/